### ISSUE TITLE
E2EE Checklist

### ISSUE THREAD

**Issue by turt2live** [turt2live/matrix-bot-sdk#134]
Basic functionality before merging [the branch](https://github.com/turt2live/matrix-bot-sdk/tree/travis/e2ee) into main:

* [x] Set up device keys
* [x] Set up One Time Keys
* [x] Keep OTKs replenished
* [x] Room encryption tracking
* [x] Device list tracking
* [x] Establish Olm sessions
* [x] Store remote-established Olm sessions
* [x] Establish Megolm outbound sessions
* [x] Store outbound Megolm sessions
* [x] Store outbound Megolm sessions as inbound sessions
* [x] Store inbound Megolm sessions
* [x] Use inbound Megolm sessions to decrypt messages
* [x] Easy send encrypted message functions
* [x] Easy decrypt messages approach
* [x] Functions to encrypt media
* [x] Functions to decrypt media
* [x] Hook up device list updates to `/sync` processing
* [x] Fallback keys: https://github.com/matrix-org/matrix-doc/pull/2732
* [x] Handle encryption of `m.relates_to` correctly.

Rolling tasks:
* [x] Unit tests for e42a44b1b3868c5889b326d67ae9a282e3fce18e
* [x] Unit tests for bb79d522fd13961ba77513dae07803355a86ea7e
* [x] Unit tests for 68911aab913e8956b8942f312cd3bf589098db34
* [x] Unit tests for 028635c71b351b38ae54e10bfdf2a076317099c4
* [x] Unit tests for d96a873b79a855ad5319fd793870f7d04b8961a5
* [x] Fix https://github.com/turt2live/matrix-bot-sdk/issues/131
* [x] Make `SynchronousMatrixClient` support this stuff (no explicit support needed)

Future (deliberately not part of this issue):
* Send/receive keyshare requests (requires device verification)
* Verification
* Blocking devices
* Cross-signing / SSSS
* Key backup
* anything else not covered in the first list
